### ISSUE TITLE
Builds require `install_name_tool` after compiling

### ISSUE THREAD

**Issue by ivabus** [human-solutions/xcframework#12]
I have to patch the internal paths of my dylibs with the command `install_name_tool` to correctly link them. My `Cargo.toml` file contains the following commands:
```toml
...
[package.metadata.xcframework]
include-dir = "src"
lib-type = "cdylib"
zip = false
macOS = true
iOS = true
simulators = true
...
```

Commands I use to patch:

```
install_name_tool -id "@rpath/libmonolib_ios.dylib" libmonolib_ios.dylib
```

The initial paths look like this: `/Users/ivabus/my/lonelyradio/target/aarch64-apple-ios/release/deps/libmonolib.dylib`, which is obviously not present on the iOS device

Without the patch my program crashes immediately with such log:

![telegram-cloud-photo-size-2-5429361935645792987-y](https://github.com/human-solutions/xcframework/assets/71599788/7bd4428c-8c87-4367-aea3-c09b6fadc0e5)

Is this a problem with the xcframework?
